import gorilla
import argparse
import os
import sys
from PIL import Image
import os.path as osp
import numpy as np
import random
import importlib
import json

import torch
import torchvision.transforms as transforms
import cv2

import open3d as o3d

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, '..', 'Pose_Estimation_Model')
sys.path.append(os.path.join(ROOT_DIR, 'provider'))
sys.path.append(os.path.join(ROOT_DIR, 'utils'))
sys.path.append(os.path.join(ROOT_DIR, 'model'))
sys.path.append(os.path.join(BASE_DIR, 'model', 'pointnet2'))


def get_parser():
    parser = argparse.ArgumentParser(
        description="Pose Estimation")
    # pem
    parser.add_argument("--gpus",
                        type=str,
                        default="0",
                        help="path to pretrain model")
    parser.add_argument("--model",
                        type=str,
                        default="pose_estimation_model",
                        help="path to model file")
    parser.add_argument("--config",
                        type=str,
                        default="config/base.yaml",
                        help="path to config file, different config.yaml use different config")
    parser.add_argument("--iter",
                        type=int,
                        default=600000,
                        help="epoch num. for testing")
    parser.add_argument("--exp_id",
                        type=int,
                        default=0,
                        help="")
    
    # input
    parser.add_argument("--output_dir", nargs="?", help="Path to root directory of the output")
    parser.add_argument("--cad_path", nargs="?", help="Path to CAD(mm)")
    parser.add_argument("--rgb_path", nargs="?", help="Path to RGB image")
    parser.add_argument("--depth_path", nargs="?", help="Path to Depth image(mm)")
    parser.add_argument("--cam_path", nargs="?", help="Path to camera information")
    parser.add_argument("--seg_path", nargs="?", help="Path to segmentation information(generated by ISM)")
    parser.add_argument("--det_score_thresh", default=0.2, help="The score threshold of detection")
    args_cfg = parser.parse_args()

    return args_cfg

def init():
    args = get_parser()
    exp_name = args.model + '_' + \
        osp.splitext(args.config.split("/")[-1])[0] + '_id' + str(args.exp_id)
    log_dir = osp.join("log", exp_name)

    cfg = gorilla.Config.fromfile(args.config)
    cfg.exp_name = exp_name
    cfg.gpus     = args.gpus
    cfg.model_name = args.model
    cfg.log_dir  = log_dir
    cfg.test_iter = args.iter

    cfg.output_dir = args.output_dir
    cfg.cad_path = args.cad_path
    cfg.rgb_path = args.rgb_path
    cfg.depth_path = args.depth_path
    cfg.cam_path = args.cam_path
    cfg.seg_path = args.seg_path

    cfg.det_score_thresh = args.det_score_thresh
    gorilla.utils.set_cuda_visible_devices(gpu_ids = cfg.gpus)

    return  cfg



from data_utils import (
    load_im,
    get_bbox,
    get_point_cloud_from_depth,
    get_resize_rgb_choose,
)
from draw_utils import draw_detections, calculate_2d_projections, draw_3d_pts
import pycocotools.mask as cocomask
import trimesh

rgb_transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                                    std=[0.229, 0.224, 0.225])])

def visualize(rgb, pred_rot, pred_trans, model_points, K, save_path):
    img = draw_detections(rgb, pred_rot, pred_trans, model_points, K, color=(255, 0, 0))
    img = Image.fromarray(np.uint8(img))
    img.save(save_path)
    prediction = Image.open(save_path)
    
    # concat side by side in PIL
    rgb = Image.fromarray(np.uint8(rgb))
    img = np.array(img)
    concat = Image.new('RGB', (img.shape[1] + prediction.size[0], img.shape[0]))
    concat.paste(rgb, (0, 0))
    concat.paste(prediction, (img.shape[1], 0))
    return concat

def visualize_projected_points(rgb, pts_3d, K, save_path="projected_points.png", color=(0, 255, 0), size=2):
    """
    Draws 2D points projected from masked 3D points onto a new image and saves it.

    Args:
        rgb: The RGB image (numpy array, shape [H, W, 3]).
        pts_3d: The masked 3D points (numpy array, shape [N, 3] or [3, N]).
        K: The camera intrinsic matrix (numpy array, shape [3, 3]).
        save_path: Path to save the output image.
        color: Color for drawing points (default: green).
        size: Size of the points (default: 2).
    Returns:
        img_pil: The output PIL image.
    """
    import numpy as np
    from PIL import Image

    point_cloud = trimesh.PointCloud(pts_3d)
    filename = f"{save_path}.ply"
    point_cloud.export(filename)

    # Ensure pts_3d shape is [3, N]
    if pts_3d.shape[0] != 3 and pts_3d.shape[1] == 3:
        pts_3d = pts_3d.T
    
    # Project 3D points to 2D
    projected_pts = calculate_2d_projections(pts_3d, K)  # shape: (N, 2)

    # Prepare image for drawing
    img = rgb.copy()
    if img.dtype != np.uint8:
        img = (img * 255).astype(np.uint8)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    # Draw points
    img_with_points = draw_3d_pts(img, projected_pts, color=color, size=size)

    # Save and return image
    img_pil = Image.fromarray(cv2.cvtColor(img_with_points, cv2.COLOR_BGR2RGB))
    img_pil.save(save_path)
    return img_pil

def _get_template(path, cfg, tem_index=1):
    rgb_path = os.path.join(path, 'rgb_'+str(tem_index)+'.png')
    mask_path = os.path.join(path, 'mask_'+str(tem_index)+'.png')
    xyz_path = os.path.join(path, 'xyz_'+str(tem_index)+'.npy')

    rgb = load_im(rgb_path).astype(np.uint8)
    xyz = np.load(xyz_path).astype(np.float32) / 1000.0  
    mask = load_im(mask_path).astype(np.uint8) == 255

    bbox = get_bbox(mask)
    y1, y2, x1, x2 = bbox
    mask = mask[y1:y2, x1:x2]

    rgb = rgb[:,:,::-1][y1:y2, x1:x2, :]
    if cfg.rgb_mask_flag:
        rgb = rgb * (mask[:,:,None]>0).astype(np.uint8)

    rgb = cv2.resize(rgb, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_LINEAR)
    rgb = rgb_transform(np.array(rgb))

    choose = (mask>0).astype(np.float32).flatten().nonzero()[0]
    if len(choose) <= cfg.n_sample_template_point:
        choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_template_point)
    else:
        choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_template_point, replace=False)
    choose = choose[choose_idx]
    xyz = xyz[y1:y2, x1:x2, :].reshape((-1, 3))[choose, :]

    rgb_choose = get_resize_rgb_choose(choose, [y1, y2, x1, x2], cfg.img_size)
    return rgb, rgb_choose, xyz


def get_templates(path, cfg):
    n_template_view = cfg.n_template_view
    all_tem = []
    all_tem_choose = []
    all_tem_pts = []

    total_nView = 42
    for v in range(n_template_view):
        i = int(total_nView / n_template_view * v)
        tem, tem_choose, tem_pts = _get_template(path, cfg, i)
        all_tem.append(torch.FloatTensor(tem).unsqueeze(0).cuda())
        all_tem_choose.append(torch.IntTensor(tem_choose).long().unsqueeze(0).cuda())
        all_tem_pts.append(torch.FloatTensor(tem_pts).unsqueeze(0).cuda())
    return all_tem, all_tem_pts, all_tem_choose

def draw_registration_result(source, target, transformation):
    import copy
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    # o3d.visualization.draw_geometries([source_temp, target_temp],
    #                                   zoom=0.4459,
    #                                   front=[0.9288, -0.2951, -0.2242],
    #                                   lookat=[1.6784, 2.0612, 1.4451],
    #                                   up=[-0.3402, -0.9189, -0.1996])
    o3d.visualization.draw_geometries([source_temp, target_temp])

def get_test_data(rgb_path, depth_path, cam_path, cad_path, seg_path, det_score_thresh, cfg):
    dets = []
    with open(seg_path) as f:
        dets_ = json.load(f) # keys: scene_id, image_id, category_id, bbox, score, segmentation
    for det in dets_:
        if det['score'] > det_score_thresh:
            dets.append(det)
    del dets_
    print("ninstance before filtering: ", len(dets))

    cam_info = json.load(open(cam_path))
    K = np.array(cam_info['cam_K']).reshape(3, 3)

    whole_image = load_im(rgb_path).astype(np.uint8)
    if len(whole_image.shape)==2:
        whole_image = np.concatenate([whole_image[:,:,None], whole_image[:,:,None], whole_image[:,:,None]], axis=2)
    whole_depth = load_im(depth_path).astype(np.float32) * cam_info['depth_scale'] / 1000.0
    # whole_depth = np.fromfile(depth_path, dtype=np.uint16).reshape(480, 640) * cam_info['depth_scale'] / 1000.0
    # print("Depth shape:", whole_depth.size)
    whole_pts = get_point_cloud_from_depth(whole_depth, K)
    # point_cloud = trimesh.load(depth_path)
    # whole_pts = np.array(point_cloud.vertices).astype(np.float32).reshape(480, 640, 3)
    print("Point cloud shape:", whole_pts.shape)

    mesh = trimesh.load_mesh(cad_path)
    model_points = mesh.sample(cfg.n_sample_model_point).astype(np.float32) / 1000.0
    radius = np.max(np.linalg.norm(model_points, axis=1))
    print("radius: ", radius)


    all_rgb = []
    all_cloud = []
    all_rgb_choose = []
    all_score = []
    all_dets = []
    for inst in dets:
        seg = inst['segmentation']
        score = inst['score']

        # mask
        h,w = seg['size']
        try:
            rle = cocomask.frPyObjects(seg, h, w)
        except:
            rle = seg
        mask = cocomask.decode(rle)
        mask = np.logical_and(mask > 0, whole_depth > 0)
        if np.sum(mask) > 32:
            bbox = get_bbox(mask)
            y1, y2, x1, x2 = bbox
        else:
            continue
        mask = mask[y1:y2, x1:x2]
        # mask_offset = np.zeros_like(mask)
        # mask_offset[:, 5:] = mask[:, :-5]
        # mask = mask_offset
        choose = mask.astype(np.float32).flatten().nonzero()[0]
        print("npts before cropping: ", len(choose))

        # pts
        cloud = whole_pts.copy()[y1:y2, x1:x2, :].reshape(-1, 3)[choose, :] 
        center = np.mean(cloud, axis=0)
        tmp_cloud = cloud - center[None, :]
        flag = np.linalg.norm(tmp_cloud, axis=1) < radius * 1.2
        if np.sum(flag) < 4:
            continue
        choose = choose[flag]
        cloud = cloud[flag]
        print("npts after cropping: ", len(cloud))

        if len(choose) <= cfg.n_sample_observed_point:
            choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_observed_point)
        else:
            choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_observed_point, replace=False)
        choose = choose[choose_idx]
        cloud = cloud[choose_idx]

        # rgb
        rgb = whole_image.copy()[y1:y2, x1:x2, :][:,:,::-1]
        if cfg.rgb_mask_flag:
            rgb = rgb * (mask[:,:,None]>0).astype(np.uint8)
        rgb = cv2.resize(rgb, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_LINEAR)
        rgb = rgb_transform(np.array(rgb))
        rgb_choose = get_resize_rgb_choose(choose, [y1, y2, x1, x2], cfg.img_size)

        all_rgb.append(torch.FloatTensor(rgb))
        all_cloud.append(torch.FloatTensor(cloud))
        all_rgb_choose.append(torch.IntTensor(rgb_choose).long())
        all_score.append(score)
        all_dets.append(inst)

    ret_dict = {}
    print("all_cloud shape: ", len(all_cloud))
    ret_dict['pts'] = torch.stack(all_cloud).cuda()
    ret_dict['rgb'] = torch.stack(all_rgb).cuda()
    ret_dict['rgb_choose'] = torch.stack(all_rgb_choose).cuda()
    ret_dict['score'] = torch.FloatTensor(all_score).cuda()

    ninstance = ret_dict['pts'].size(0)
    ret_dict['model'] = torch.FloatTensor(model_points).unsqueeze(0).repeat(ninstance, 1, 1).cuda()
    ret_dict['K'] = torch.FloatTensor(K).unsqueeze(0).repeat(ninstance, 1, 1).cuda()
    return ret_dict, whole_image, whole_pts.reshape(-1, 3), model_points, all_dets



if __name__ == "__main__":
    cfg = init()

    random.seed(cfg.rd_seed)
    torch.manual_seed(cfg.rd_seed)

    # model
    print("=> creating model ...")
    MODEL = importlib.import_module(cfg.model_name)
    model = MODEL.Net(cfg.model)
    model = model.cuda()
    model.eval()
    checkpoint = os.path.join(os.path.dirname((os.path.abspath(__file__))), 'checkpoints', 'sam-6d-pem-base.pth')
    gorilla.solver.load_checkpoint(model=model, filename=checkpoint)

    print("=> extracting templates ...")
    tem_path = os.path.join(cfg.output_dir, 'templates')
    all_tem, all_tem_pts, all_tem_choose = get_templates(tem_path, cfg.test_dataset)
    with torch.no_grad():
        all_tem_pts, all_tem_feat = model.feature_extraction.get_obj_feats(all_tem, all_tem_pts, all_tem_choose)

    print("=> loading input data ...")
    input_data, img, whole_pts, model_points, detections = get_test_data(
        cfg.rgb_path, cfg.depth_path, cfg.cam_path, cfg.cad_path, cfg.seg_path, 
        cfg.det_score_thresh, cfg.test_dataset
    )
    ninstance = input_data['pts'].size(0)
    
    print("=> running model ...")
    with torch.no_grad():
        input_data['dense_po'] = all_tem_pts.repeat(ninstance,1,1)
        input_data['dense_fo'] = all_tem_feat.repeat(ninstance,1,1)
        out = model(input_data)

    if 'pred_pose_score' in out.keys():
        pose_scores = out['pred_pose_score'] * out['score']
    else:
        pose_scores = out['score']
    pose_scores = pose_scores.detach().cpu().numpy()
    pred_rot = out['pred_R'].detach().cpu().numpy()
    pred_trans = out['pred_t'].detach().cpu().numpy() * 1000

    print("=> saving results ...")
    os.makedirs(f"{cfg.output_dir}/sam6d_results", exist_ok=True)
    for idx, det in enumerate(detections):
        detections[idx]['score'] = float(pose_scores[idx])
        detections[idx]['R'] = list(pred_rot[idx].tolist())
        detections[idx]['t'] = list(pred_trans[idx].tolist())

    with open(os.path.join(f"{cfg.output_dir}/sam6d_results", 'detection_pem.json'), "w") as f:
        json.dump(detections, f)

    print("=> visualizating ...")
    # Save each pose result to a separate image
    for idx in range(ninstance):
        save_path = os.path.join(f"{cfg.output_dir}/sam6d_results", f'vis_pem_{idx}.png')
        K = input_data['K'][idx:idx+1].detach().cpu().numpy()  # shape (1, 3, 3)
        vis_img = visualize(
            img,
            pred_rot[idx:idx+1],
            pred_trans[idx:idx+1],
            model_points*1000,
            K,
            save_path
        )
        print(f"pred_rot[{idx}]: ", pred_rot[idx])
        print(f"pred_trans[{idx}]: ", pred_trans[idx])
        vis_img.save(save_path)
    print("=> visualizing projected points ...")

    for idx in range(ninstance):
        # Get 3D points and camera intrinsics
        pts_3d = input_data['pts'][idx].cpu().numpy()  # shape: (N, 3) or (3, N)
        K = input_data['K'][idx].cpu().numpy()  # shape: (3, 3)
        save_path = os.path.join(f"{cfg.output_dir}/sam6d_results/projected_points", f"projected_points_{idx}.png")
        visualize_projected_points(img, pts_3d, K, save_path=save_path)

    print("=> visualizing whole 3D points ...")
    point_cloud = trimesh.PointCloud(model_points)
    save_path = os.path.join(f"{cfg.output_dir}/sam6d_results/projected_points", f"whole_points.ply")
    point_cloud.export(save_path)
    
    # --- Refine best pose with Open3D ICP ---
    print("=> refining best pose with Open3D ICP ...")
    # Find best pose index
    best_idx = int(np.argmax(pose_scores))
    print(f"Best pose index: {best_idx}")
    # Get observed point cloud (from input_data['pts'])
    observed_pts = input_data['pts'][best_idx].cpu().numpy()  # (N, 3)
    # Get model points (CAD)
    model_pts = model_points  # (M, 3), already in mm
    # Initial pose
    init_rot = pred_rot[best_idx]  # (3, 3)
    init_trans = pred_trans[best_idx] / 1000.0  # (3,), convert mm to meters
    # Transform model points with initial pose
    model_pts_transformed = (init_rot @ model_pts.T).T + init_trans
    # Convert to Open3D point clouds
    pcd_obs = o3d.geometry.PointCloud()
    pcd_obs.points = o3d.utility.Vector3dVector(observed_pts)
    pcd_model = o3d.geometry.PointCloud()
    pcd_model.points = o3d.utility.Vector3dVector(model_pts_transformed)
    # ICP registration
    threshold = 10.0  # mm, adjust as needed
    reg_p2p = o3d.pipelines.registration.registration_icp(
        pcd_model, pcd_obs, threshold,
        np.eye(4),
        o3d.pipelines.registration.TransformationEstimationPointToPoint()
    )
    # Extract refined transformation
    refined_transform = reg_p2p.transformation  # 4x4
    refined_rot = refined_transform[:3, :3]
    refined_trans = refined_transform[:3, 3]
    print("Refined rotation:\n", refined_rot)
    print("Refined translation:", refined_trans)
    # Visualize the refined pose and save the image
    print("=> visualizing refined pose ...")
    draw_registration_result(pcd_model, pcd_obs, refined_transform)

    # Apply refined ICP transform to the initial best pose
    # Initial pose (in meters)
    init_rot = pred_rot[best_idx]
    init_trans = pred_trans[best_idx] / 1000.0
    # Compose transforms: refined_transform @ [init_rot|init_trans]
    init_pose = np.eye(4)
    init_pose[:3, :3] = init_rot
    init_pose[:3, 3] = init_trans
    final_pose = refined_transform @ init_pose
    final_rot = final_pose[:3, :3]
    final_trans = final_pose[:3, 3]
    # For visualization, convert translation back to mm
    final_rot_batch = final_rot[np.newaxis, ...]  # (1, 3, 3)
    final_trans_batch = (final_trans * 1000.0)[np.newaxis, ...]  # (1, 3)
    K_best = input_data['K'][best_idx:best_idx+1].detach().cpu().numpy()  # (1, 3, 3)
    save_path_final = os.path.join(f"{cfg.output_dir}/sam6d_results", 'vis_pem_final.png')
    vis_img_final = visualize(
        img,
        final_rot_batch,
        final_trans_batch,
        model_points*1000,
        K_best,
        save_path_final
    )
    vis_img_final.save(save_path_final)
    print(f"Final pose visualization saved to {save_path_final}")
    

