pose_estimation:
    ros__parameters:
        sam6d_root: "/home/intel/yy/openvino_contrib/modules/3d/OV-SAM-6D/SAM-6D"
        output_dir: "/home/intel/yy/ws_sam6d_ov/validation"
        cad_path: "/home/intel/yy/logistics-box.ply"
        templates_dir: "/home/intel/yy/templates"
        detector_path: "/home/intel/yy/det"
        sam2_variant: "sam2_hiera_small"
        inference_python: "/home/intel/miniforge3/envs/ov_sam6d/bin/python"
        device: "GPU"
        precision: "fp16"
        detector_threshold: 0.2
        rgb_topic: "/camera/color/image_raw"
        depth_topic: "/camera/aligned_depth_to_color/image_raw"
        camera_info_topic: "/camera/aligned_depth_to_color/camera_info"
